### ISSUE TITLE
KeyError: '@name'

### ISSUE THREAD

**Issue by illmattic-1** [Alalalalaki/jpstat#1]
Hello,

I have successfully pulled data using the following code...
`data, note = jpstat.estat.get_data(statsDataId="0003443407")`

but with this particular number i get.... 
`KeyError: '@name'`

Can someone tell me the reason? I am not a programmer and am just looking for a convenient way to get economic data for Japan in Python.

Thank you

**Comment by Alalalalaki** [comment]
There is no error for me running this code. Can you offer some more information?

What do your mean by "this particular number"?

**Comment by illmattic-1** [comment]
This statsDataId number as well as other numbers brings up this error while other numbers work fine.

**Comment by Alalalalaki** [comment]
Again this "0003443407" works for me. Can your provide "other numbers" that create this error?

**Comment by illmattic-1** [comment]
Well so far all the numbers under the National Survey of Family Income, Consumption and Wealth haven't worked like 0003443428, 0003443450.

I was able to get data from Machinery Orders without any problems.  For Labour Force Survey some work, some don't.

**Comment by illmattic-1** [comment]
If this helps, this is the full error message

`df[cat['@name']] = df[col_name].map(cat_map)`
`KeyError: '@name`

**Comment by Alalalalaki** [comment]
Ok now I find that this problem is due to some difference in the data structure when setting language to English.

A quick fix is to use `lang=J`.  I may find some time this weekend to fix this bug for this case.

**Comment by illmattic-1** [comment]
Yes, this fixed the problem. Thank you!
Look forward to the bug being fixed. Thanks!

**Comment by illmattic-1** [comment]
The solution of changing the language to Japanese has now caused this error:

```
note = pd.DataFrame(data['STATISTICAL_DATA']['DATA_INF']['NOTE'])
                                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'NOTE'
```

**Comment by Alalalalaki** [comment]
Can you tell me the `statsDataId` that you are trying to access? It seems that this dataset has a different structure comparing to others.

**Comment by illmattic-1** [comment]
My apologies. I made a mistake.  I forgot that the English sets have different IDs than Japanese sets. I was trying an English ID number with the Japanese language. 

But I can't get access to all the datasets in the English version.

**Comment by illmattic-1** [comment]
Well actually, maybe I have that incorrect. I am doing the following:

`listt = jpstat.estat.get_list(statsCode="00100406")`

`listt
       @id STAT_NAME GOV_ORG STATISTICS_NAME     TITLE  SURVEY_DATE   OPEN_DATE  OVERALL_TOTAL_NUMBER
0  0003446461    景気動向指数     内閣府          景気動向指数      長期系列            0  2023-04-27                  5856
1  0003446462    景気動向指数     内閣府          景気動向指数   個別系列の数値            0  2023-04-27                 18482
2  0003446463    景気動向指数     内閣府          景気動向指数  個別系列の寄与度            0  2023-04-27                 14647`

`data, note = jpstat.estat.get_data(statsDataId="0003446461")`

` note = pd.DataFrame(data['STATISTICAL_DATA']['DATA_INF']['NOTE'])
                                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'NOTE'`

**Comment by Alalalalaki** [comment]
You can try `data = jpstat.estat.get_data(statsDataId="0003446461", return_note=False)`.

Each time you see there is an Error with `Note` you can simply suppress outputting note.

**Comment by Alalalalaki** [comment]
I also fix the problem with `lang="E"` in the new version. Please update through pip and see if there is still any problems.

**Comment by illmattic-1** [comment]
Thanks! I upgraded the package and now English is working with this return_note=False argument. Thanks again!
